"""initial_schema

Revision ID: 191c883fbfd6
Revises: 
Create Date: 2026-04-30 17:36:12.352933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '191c883fbfd6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('device_info', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('broker', sa.String(length=20), nullable=True),
    sa.Column('login_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('active_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_active_sessions_username', ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_sessions_username'), ['username'], unique=False)

    op.create_table('analyzer_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_type', sa.String(length=50), nullable=False),
    sa.Column('request_data', sa.Text(), nullable=False),
    sa.Column('response_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyzer_logs', schema=None) as batch_op:
        batch_op.create_index('idx_analyzer_api_type', ['api_type'], unique=False)
        batch_op.create_index('idx_analyzer_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_analyzer_type_time', ['api_type', 'created_at'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.Text(), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_mode', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index('idx_api_keys_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_api_keys_order_mode', ['order_mode'], unique=False)

    op.create_table('auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('feed_token', sa.Text(), nullable=True),
    sa.Column('broker', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('secret_api_key', sa.Text(), nullable=True),
    sa.Column('primary_ip', sa.String(length=45), nullable=True),
    sa.Column('secondary_ip', sa.String(length=45), nullable=True),
    sa.Column('ip_updated_at', sa.DateTime(), nullable=True),
    sa.Column('aux_param1', sa.Text(), nullable=True),
    sa.Column('aux_param2', sa.Text(), nullable=True),
    sa.Column('aux_param3', sa.Text(), nullable=True),
    sa.Column('aux_param4', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.create_index('idx_auth_broker', ['broker'], unique=False)
        batch_op.create_index('idx_auth_is_revoked', ['is_revoked'], unique=False)
        batch_op.create_index('idx_auth_user_id', ['user_id'], unique=False)

    op.create_table('chart_preferences',
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'key')
    )
    op.create_table('chartink_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('webhook_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_intraday', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('end_time', sa.String(length=5), nullable=True),
    sa.Column('squareoff_time', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('webhook_id')
    )
    op.create_table('flow_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nodes', sa.JSON(), nullable=True),
    sa.Column('edges', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('schedule_job_id', sa.String(length=255), nullable=True),
    sa.Column('webhook_token', sa.String(length=64), nullable=True),
    sa.Column('webhook_secret', sa.String(length=64), nullable=True),
    sa.Column('webhook_enabled', sa.Boolean(), nullable=True),
    sa.Column('webhook_auth_type', sa.String(length=20), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('webhook_token')
    )
    with op.batch_alter_table('flow_workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flow_workflows_id'), ['id'], unique=False)

    op.create_table('leverage_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leverage', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_info', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('login_type', sa.String(length=20), nullable=True),
    sa.Column('broker', sa.String(length=20), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index('idx_login_attempts_status', ['status'], unique=False)
        batch_op.create_index('idx_login_attempts_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('idx_login_attempts_username', ['username'], unique=False)

    op.create_table('market_holiday_exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holiday_id', sa.Integer(), nullable=False),
    sa.Column('exchange_code', sa.String(length=10), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.BigInteger(), nullable=True),
    sa.Column('end_time', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_holiday_exchanges', schema=None) as batch_op:
        batch_op.create_index('idx_holiday_exchange', ['holiday_id', 'exchange_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_holiday_exchanges_exchange_code'), ['exchange_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_holiday_exchanges_holiday_id'), ['holiday_id'], unique=False)

    op.create_table('market_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=False),
    sa.Column('holiday_type', sa.String(length=30), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_holidays', schema=None) as batch_op:
        batch_op.create_index('idx_holiday_date_year', ['holiday_date', 'year'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_holidays_holiday_date'), ['holiday_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_holidays_year'), ['year'], unique=False)

    op.create_table('market_timings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_code', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('start_offset', sa.BigInteger(), nullable=False),
    sa.Column('end_offset', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_timings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_timings_exchange_code'), ['exchange_code'], unique=True)

    op.create_table('order_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_type', sa.Text(), nullable=False),
    sa.Column('request_data', sa.Text(), nullable=False),
    sa.Column('response_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('api_type', sa.String(length=50), nullable=False),
    sa.Column('order_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at_ist', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at_ist', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at_ist', sa.String(length=50), nullable=True),
    sa.Column('rejected_by', sa.String(length=255), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('broker_order_id', sa.String(length=255), nullable=True),
    sa.Column('broker_status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_orders', schema=None) as batch_op:
        batch_op.create_index('idx_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_user_status', ['user_id', 'status'], unique=False)

    op.create_table('qty_freeze',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('freeze_qty', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qty_freeze', schema=None) as batch_op:
        batch_op.create_index('idx_exchange_symbol', ['exchange', 'symbol'], unique=True)
        batch_op.create_index(batch_op.f('ix_qty_freeze_exchange'), ['exchange'], unique=False)
        batch_op.create_index(batch_op.f('ix_qty_freeze_symbol'), ['symbol'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analyze_mode', sa.Boolean(), nullable=True),
    sa.Column('smtp_server', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_username', sa.String(length=255), nullable=True),
    sa.Column('smtp_password_encrypted', sa.Text(), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=True),
    sa.Column('smtp_from_email', sa.String(length=255), nullable=True),
    sa.Column('smtp_helo_hostname', sa.String(length=255), nullable=True),
    sa.Column('security_auto_ban_enabled', sa.Boolean(), nullable=True),
    sa.Column('security_404_threshold', sa.Integer(), nullable=True),
    sa.Column('security_404_ban_duration', sa.Integer(), nullable=True),
    sa.Column('security_api_threshold', sa.Integer(), nullable=True),
    sa.Column('security_api_ban_duration', sa.Integer(), nullable=True),
    sa.Column('security_repeat_offender_limit', sa.Integer(), nullable=True),
    sa.Column('paper_price_source', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('webhook_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_intraday', sa.Boolean(), nullable=True),
    sa.Column('trading_mode', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('end_time', sa.String(length=5), nullable=True),
    sa.Column('squareoff_time', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('webhook_id')
    )
    op.create_table('strategy_portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('underlying', sa.String(length=40), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('expiry', sa.String(length=20), nullable=True),
    sa.Column('legs_json', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_portfolio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_portfolio_watchlist'), ['watchlist'], unique=False)

    op.create_table('symtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('brsymbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('brexchange', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('expiry', sa.String(), nullable=True),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('lotsize', sa.Integer(), nullable=True),
    sa.Column('instrumenttype', sa.String(), nullable=True),
    sa.Column('tick_size', sa.Float(), nullable=True),
    sa.Column('contract_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('symtoken', schema=None) as batch_op:
        batch_op.create_index('idx_brsymbol_exchange', ['brsymbol', 'exchange'], unique=False)
        batch_op.create_index('idx_symbol_exchange', ['symbol', 'exchange'], unique=False)
        batch_op.create_index('idx_symbol_name', ['symbol', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_symtoken_brexchange'), ['brexchange'], unique=False)
        batch_op.create_index(batch_op.f('ix_symtoken_brsymbol'), ['brsymbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_symtoken_exchange'), ['exchange'], unique=False)
        batch_op.create_index(batch_op.f('ix_symtoken_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_symtoken_token'), ['token'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('totp_secret', sa.String(length=32), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chartink_symbol_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('chartink_symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['chartink_strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flow_workflow_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logs', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['flow_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flow_workflow_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flow_workflow_executions_id'), ['id'], unique=False)

    op.create_table('strategy_symbol_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_symbol_mappings')
    with op.batch_alter_table('flow_workflow_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flow_workflow_executions_id'))

    op.drop_table('flow_workflow_executions')
    op.drop_table('chartink_symbol_mappings')
    op.drop_table('users')
    with op.batch_alter_table('symtoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symtoken_token'))
        batch_op.drop_index(batch_op.f('ix_symtoken_symbol'))
        batch_op.drop_index(batch_op.f('ix_symtoken_exchange'))
        batch_op.drop_index(batch_op.f('ix_symtoken_brsymbol'))
        batch_op.drop_index(batch_op.f('ix_symtoken_brexchange'))
        batch_op.drop_index('idx_symbol_name')
        batch_op.drop_index('idx_symbol_exchange')
        batch_op.drop_index('idx_brsymbol_exchange')

    op.drop_table('symtoken')
    with op.batch_alter_table('strategy_portfolio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_portfolio_watchlist'))

    op.drop_table('strategy_portfolio')
    op.drop_table('strategies')
    op.drop_table('settings')
    with op.batch_alter_table('qty_freeze', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qty_freeze_symbol'))
        batch_op.drop_index(batch_op.f('ix_qty_freeze_exchange'))
        batch_op.drop_index('idx_exchange_symbol')

    op.drop_table('qty_freeze')
    with op.batch_alter_table('pending_orders', schema=None) as batch_op:
        batch_op.drop_index('idx_user_status')
        batch_op.drop_index('idx_created_at')

    op.drop_table('pending_orders')
    op.drop_table('order_logs')
    with op.batch_alter_table('market_timings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_timings_exchange_code'))

    op.drop_table('market_timings')
    with op.batch_alter_table('market_holidays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_holidays_year'))
        batch_op.drop_index(batch_op.f('ix_market_holidays_holiday_date'))
        batch_op.drop_index('idx_holiday_date_year')

    op.drop_table('market_holidays')
    with op.batch_alter_table('market_holiday_exchanges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_holiday_exchanges_holiday_id'))
        batch_op.drop_index(batch_op.f('ix_market_holiday_exchanges_exchange_code'))
        batch_op.drop_index('idx_holiday_exchange')

    op.drop_table('market_holiday_exchanges')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index('idx_login_attempts_username')
        batch_op.drop_index('idx_login_attempts_timestamp')
        batch_op.drop_index('idx_login_attempts_status')

    op.drop_table('login_attempts')
    op.drop_table('leverage_config')
    with op.batch_alter_table('flow_workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flow_workflows_id'))

    op.drop_table('flow_workflows')
    op.drop_table('chartink_strategies')
    op.drop_table('chart_preferences')
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.drop_index('idx_auth_user_id')
        batch_op.drop_index('idx_auth_is_revoked')
        batch_op.drop_index('idx_auth_broker')

    op.drop_table('auth')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index('idx_api_keys_order_mode')
        batch_op.drop_index('idx_api_keys_created_at')

    op.drop_table('api_keys')
    with op.batch_alter_table('analyzer_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_analyzer_type_time')
        batch_op.drop_index('idx_analyzer_created_at')
        batch_op.drop_index('idx_analyzer_api_type')

    op.drop_table('analyzer_logs')
    with op.batch_alter_table('active_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_active_sessions_username'))
        batch_op.drop_index('idx_active_sessions_username')

    op.drop_table('active_sessions')
    # ### end Alembic commands ###
